name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm 5
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.x.x

      - name: pnpm install
        run: pnpm install

      - name: Compile
        run: npm run build-debug

      - name: Test
        run: npm test

  release:
    name: Publish binaries
    needs: test
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm 5
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.x.x

      - name: pnpm install
        run: pnpm install

      - name: Build .node
        run: npm run build

      - name: Pre-minify .tar size
        run: npm run minify

      - name: Pack up .tar
        run: npm run package

      - name: Upload .tar to GitHub releases
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run upload-binary
